// Code generated by "stringer -type CompressionMethod compression_methods.go"; DO NOT EDIT.

package main

import "fmt"

const _CompressionMethod_name = "zstdgzipraw"

var _CompressionMethod_index = [...]uint8{0, 4, 8, 11}

func (i CompressionMethod) String() string {
	if i < 0 || i >= CompressionMethod(len(_CompressionMethod_index)-1) {
		return fmt.Sprintf("CompressionMethod(%d)", i)
	}
	return _CompressionMethod_name[_CompressionMethod_index[i]:_CompressionMethod_index[i+1]]
}
